version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gestor_backend
    restart: always
    environment:
      - USE_SQLITE=true
    ports:
      - "8000:8000"
    volumes:
      - backend_db_data:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gestor_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  backend_db_data:
